Repository Jmurp11/draft-shark, pull requests merged in 2020-03, with the labels that each got.

#57 clean up authentication
  client/package-lock.json
  client/package.json
  client/src/app/app.component.ts
  client/src/app/auth/auth.service.ts
  client/src/app/auth/login/login.component.ts
  client/src/app/auth/queries.ts
  client/src/app/auth/register/register.component.ts
  client/src/app/auth/user.model.ts
  client/src/app/graphql.module.ts
  client/src/app/navbar/navbar.component.html
  client/src/app/navbar/navbar.component.ts
  client/src/app/notes/note-card/note-card.component.ts
  client/src/app/notes/note.service.ts
  client/src/app/notes/note/note.component.ts
  server/src/modules/user/UserResolver.ts
  server/src/modules/user/inputs/LogoutInput.ts
  server/src/modules/user/inputs/index.ts
Labels: bug

#62 clean up UI
  client/src/app/notes/note-card/note-card.component.css
  client/src/app/notes/note/note.component.css
  client/src/app/notes/note/note.component.html
Labels: bug

#63 Develop
  client/src/app/app.module.ts
  client/src/app/dashboard/dashboard.component.css
  client/src/app/dashboard/dashboard.component.html
  client/src/app/dashboard/dashboard.component.ts
  client/src/app/notes/note-card/note-card.component.ts
  client/src/app/player-table/player-table.component.html
  client/src/app/player-table/player-table.component.ts
  client/src/app/player-table/queries.ts
  client/src/app/target/add-target/add-target.component.css
  client/src/app/target/add-target/add-target.component.html
  client/src/app/target/add-target/add-target.component.spec.ts
  client/src/app/target/add-target/add-target.component.ts
  client/src/app/target/queries.ts
  client/src/app/target/target-dialog/target-dialog.component.css
  client/src/app/target/target-dialog/target-dialog.component.html
  client/src/app/target/target-dialog/target-dialog.component.spec.ts
  client/src/app/target/target-dialog/target-dialog.component.ts
  client/src/app/target/target.component.css
  client/src/app/target/target.component.html
  client/src/app/target/target.component.spec.ts
  client/src/app/target/target.component.ts
  client/src/app/target/target.model.ts
  client/src/app/target/target.service.spec.ts
  client/src/app/target/target.service.ts
  server/src/entity/Player.ts
  server/src/entity/Target.ts
  server/src/entity/index.ts
  server/src/modules/index.ts
  server/src/modules/projection/ProjectionResolver.ts
  server/src/modules/target/TargetResolver.ts
  server/src/modules/target/inputs/TargetInput.ts
Labels: enhancement

#66 Develop
  client/src/app/app.component.css
  client/src/app/app.component.html
  client/src/app/app.module.ts
  client/src/app/dashboard/dashboard.component.css
  client/src/app/dashboard/dashboard.component.html
  client/src/app/footer/footer.component.css
  client/src/app/footer/footer.component.html
  client/src/app/footer/footer.component.spec.ts
  client/src/app/footer/footer.component.ts
  client/src/app/notes/note-card/note-card.component.html
  client/src/app/notes/note-card/note-card.component.ts
  client/src/app/notes/note.service.ts
  client/src/app/notes/public-notes/public-notes.component.html
  client/src/app/notes/public-notes/public-notes.component.ts
  client/src/app/notes/queries.ts
  client/src/app/notes/user-notes/user-notes.component.html
  client/src/app/notes/user-notes/user-notes.component.ts
  client/src/app/target/target.component.html
  client/src/styles.css
  server/src/modules/note/NoteResolver.ts
Labels: enhancement

#67 Develop
  client/angular.json
  client/package-lock.json
  client/package.json
  client/src/app/app.component.css
  client/src/app/app.component.html
  client/src/app/app.module.ts
  client/src/app/dashboard/dashboard.component.css
  client/src/app/dashboard/dashboard.component.html
  client/src/app/dashboard/dashboard.component.ts
  client/src/app/footer/footer.component.css
  client/src/app/footer/footer.component.html
  client/src/app/navbar/navbar.component.css
  client/src/app/navbar/navbar.component.html
  client/src/app/navbar/navbar.component.ts
  client/src/app/notes/note.service.ts
  client/src/app/notes/note/note.component.ts
  client/src/app/notes/public-notes/public-notes.component.html
  client/src/app/notes/public-notes/public-notes.component.ts
  client/src/app/shared/loading-spinner/loading-spinner.component.css
  client/src/app/sidenav/sidenav.component.css
  client/src/app/sidenav/sidenav.component.html
  client/src/app/sidenav/sidenav.component.spec.ts
  client/src/app/sidenav/sidenav.component.ts
  client/src/app/target/add-target/add-target.component.ts
  client/src/app/target/target.component.ts
  client/src/app/target/target.service.ts
  client/src/styles.scss
Labels: enhancement

#70 Develop
  client/src/app/app.component.html
  client/src/app/dashboard/dashboard.component.html
  client/src/app/dashboard/dashboard.component.ts
  client/src/app/notes/note-card/note-card.component.html
  client/src/app/notes/note.service.ts
  client/src/app/notes/public-notes/public-notes.component.html
  client/src/app/notes/user-notes/user-notes.component.html
  client/src/app/notes/user-notes/user-notes.component.ts
  client/src/app/sidenav/sidenav.component.html
  client/src/app/target/target.component.css
Labels: enhancement

#83 update logo
  client/src/app/navbar/navbar.component.css
  client/src/app/navbar/navbar.component.html
  client/src/app/navbar/navbar.component.ts
  client/src/assets/images/logo-full.svg
  client/src/assets/images/shark-head.svg
Labels: enhancement

#91 Feature/ui fix
  client/src/app/app.component.css
  client/src/app/dashboard/dashboard.component.css
  client/src/app/dashboard/dashboard.component.html
  client/src/app/notes/public-notes/public-notes.component.css
  client/src/app/notes/user-notes/user-notes.component.css
  client/src/app/player-table/player-table.component.css
  client/src/styles.scss
Labels: bug

#92 Develop
  client/src/app/app.component.css
  client/src/app/dashboard/dashboard.component.css
  client/src/app/dashboard/dashboard.component.html
  client/src/app/notes/public-notes/public-notes.component.css
  client/src/app/notes/user-notes/user-notes.component.css
  client/src/app/player-table/player-table.component.css
  client/src/styles.scss
Labels: enhancement

#93 Develop
  client/src/app/app.component.ts
  client/src/app/player-table/queries.ts
  client/src/app/target/add-target/add-target.component.ts
  client/src/assets/images/shark-head.svg
Labels: dependencies

#94 ui fixes. clean up broken screen on login
  client/src/app/dashboard/dashboard.component.ts
  client/src/app/notes/note.service.ts
  client/src/app/notes/note/note.component.ts
  client/src/app/notes/public-notes/public-notes.component.ts
  client/src/app/notes/user-notes/user-notes.component.ts
  client/src/app/sidenav/sidenav.component.ts
  client/src/app/target/target.component.ts
Labels: bug

#96 Develop
  client/src/app/dashboard/dashboard.component.ts
Labels: bug

#97 Develop
  client/src/app/app.component.ts
  client/src/app/auth/auth.service.ts
  client/src/app/dashboard/dashboard.component.ts
  client/src/app/graphql.module.ts
  client/src/app/notes/note/note.component.ts
  client/src/app/target/target.component.ts
  server/src/entity/User.ts
  server/src/index.ts
  server/src/middleware/isAuth.ts
  server/src/modules/user/UserResolver.ts
  server/src/shared/auth.ts
Labels: bug

#110 Feature/profile image
  client/src/app/auth/auth.service.ts
  client/src/app/auth/queries.ts
  client/src/app/auth/register/register.component.html
  client/src/app/auth/register/register.component.ts
  client/src/app/notes/note.model.ts
  client/src/app/notes/public-notes/public-notes.component.css
  client/src/app/notes/public-notes/public-notes.component.html
  client/src/app/notes/queries.ts
  client/src/app/notes/user-notes/user-notes.component.css
  client/src/app/notes/user-notes/user-notes.component.html
  client/src/styles.scss
  server/src/entity/User.ts
  server/src/modules/user/UserResolver.ts
  server/src/modules/user/inputs/RegisterInput.ts
Labels: enhancement

#111 Develop
  client/src/app/auth/auth.service.ts
  client/src/app/auth/queries.ts
  client/src/app/auth/register/register.component.html
  client/src/app/auth/register/register.component.ts
  client/src/app/notes/note.model.ts
  client/src/app/notes/public-notes/public-notes.component.css
  client/src/app/notes/public-notes/public-notes.component.html
  client/src/app/notes/queries.ts
  client/src/app/notes/user-notes/user-notes.component.css
  client/src/app/notes/user-notes/user-notes.component.html
  client/src/styles.scss
  server/src/entity/User.ts
  server/src/modules/user/UserResolver.ts
  server/src/modules/user/inputs/RegisterInput.ts
Labels: enhancement

#112 fix liked images
  client/src/app/notes/liked-notes/liked-notes.component.css
  client/src/app/notes/liked-notes/liked-notes.component.html
  client/src/app/notes/queries.ts
Labels: bug

#113 Develop
  client/src/app/layout/navbar/navbar.component.ts
Labels: bug
